In [4]:
import numpy as np
import scipy as sp
import seaborn as sns
import random
from matplotlib import pyplot as plt
from scipy.spatial.distance import pdist, squareform

def tri(zd, H):
    zd = zd.T
    H=H-H[0]
    tmp = zd[0]
    tmp = tmp * tmp
    zd = np.delete(zd,(0), axis=0)
    r1=np.multiply(zd,zd)
    Ha=np.delete(H,(0), axis=0)
    K=np.multiply(Ha,Ha)
    K=K.sum(axis=1)
    b= 0.5*(K-r1+tmp) 
    S_inv = np.linalg.inv(Ha.T*Ha)*Ha.T
    x_hat = S_inv*b
    return x_hat  

def loc(x1):
    H = np.array([[7.54,0],[7.54,7.21],[14.14,0],[14.14,7.58]])
    H2 = np.matrix([[7.54,0],[7.54,7.21],[14.14,0],[14.14,7.58]])
    d = x1-H
    d = np.multiply(d,d)
    d = np.sqrt(d.sum(axis=1))
    zd = np.matrix([d[0],d[1],d[2],d[3]])
    #zd = np.array([d[0],d[1],d[2],d[3]])
    #print(zd)

    d[0] = d[0] + np.random.normal(0,0.5,1)
    d[1] = d[1] + np.random.normal(0,0.5,1)
    d[2] = d[2] + np.random.normal(0,0.5,1)
    d[3] = d[3] + np.random.normal(0,0.5,1)
      
    zd2 = np.matrix([d[0],d[1],d[2],d[3]])
    zd3 = np.array([d[0],d[1],d[2],d[3]])
    zd = np.matrix([d[0],d[1],d[2],d[3]])
    x_hat = tri(zd,H2)
    x_hat = x_hat.T+H[0]
    return x_hat

j = 0
cdf = np.random.random(100)

for j in range(0,100):
    x1 = np.array([15*random.random(),15*random.random()])
    x2 = np.array([15*random.random(),15*random.random()])
    print(x1)
    print(x2)
    x1_gn = loc(x1)
    x2_gn = loc(x2)
    print(x1_gn)
    print(x2_gn)
    zd = zd.T
    H=H-H[0]
    tmp = zd[0]
    tmp = tmp * tmp
    zd = np.delete(zd,(0), axis=0)
    r1=np.multiply(zd,zd)
    Ha=np.delete(H,(0), axis=0)
    K=np.multiply(Ha,Ha)
    K=K.sum(axis=1)
    b= 0.5*(K-r1+tmp) 

    y1 = x1_gn*Ha-b

[ 3.52127827 12.24337935]
[ 7.48564057 10.4608805 ]
[[ 5.51785733 12.46717493]]
[[ 7.37081792 10.16945192]]


NameError: name 'zd' is not defined

In [38]:
x = np.array([15*random.random(),15*random.random()])
print(x)
H = np.array([[7.54,0],[7.54,7.21],[14.14,0],[14.14,7.58]])
H2 = np.matrix([[7.54,0],[7.54,7.21],[14.14,0],[14.14,7.58]])
d = x-H
d = np.multiply(d,d)
d = np.sqrt(d.sum(axis=1))
zd = np.matrix([2.79141785, 2.68082355, 7.54493688, 7.01732975])
x_hat = tri(zd, H2)
x_hat = x_hat.T+H[0]
print(x_hat)

[10.08225007  5.64266098]
[[10.93874831  3.69787876]
 [ 8.4463567   1.47628399]
 [ 8.83135306  1.81945072]]


In [27]:
print(sum(np.power((x_hat-x))))

ValueError: invalid number of arguments

In [47]:
cdf = np.ones((1,100))
print(cdf.item(0))

1.0


In [61]:
data = np.random.randn(10000)
print(type(data))

<class 'numpy.ndarray'>


In [4]:
pip install emcee

     |████████████████████████████████| 41 kB 140 kB/s eta 0:00:011
Note: you may need to restart the kernel to use updated packages.


In [5]:
print(x_hat.item(0))

10.908422322088718
