In [5]:
# Ranging #
from pypozyx import *
import numpy as np
from pypozyx.definitions.registers import *
import sys
import time
import serial 
from numpy.linalg import inv
from openpyxl import Workbook
write_wb = Workbook()
write_ws = write_wb.active

def tri(zd, H):
    zd = zd.T
    H=H-H[0]
    tmp = zd[0]
    tmp = tmp * tmp
    zd = np.delete(zd,(0), axis=0)
    r1=np.multiply(zd,zd)
    Ha=np.delete(H,(0), axis=0)
    K=np.multiply(Ha,Ha)
    K=K.sum(axis=1)
    b= 0.5*(K-r1+tmp) 
    S_inv = np.linalg.inv(Ha.T*Ha)*Ha.T
    x_hat = S_inv*b
    return x_hat

########################################## RANGING ##############################################
j = 0   
port = '/dev/cu.usbmodem328B345A30371'#'/dev/cu.usbmodem3998326833361'
p = PozyxSerial(port)

remote_id = 0x696a          # the network ID of the remote device
remote = True               # whether to use the given remote device for ranging
if not remote:
    remote_id = None
th = 1000
dt = 1
while True:
    ser = serial.Serial(port=port,baudrate=28800, timeout = 1)
    #print ser

    destination_id_1 = 0x6966      # network ID of the ranging destination
    range_step_mm = 1000         # distance that separates the amount of LEDs lighting up.
    device_range_1 = DeviceRange()
    status_1 = p.doRanging(destination_id_1, device_range_1, remote_id)
    zd_1= device_range_1[1]
    print(device_range_1[1])
    
    destination_id_2 = 0x675a      # network ID of the ranging destination
    range_step_mm = 1000         # distance that separates the amount of LEDs lighting up.
    device_range_2 = DeviceRange()
    status_2 = p.doRanging(destination_id_2, device_range_2, remote_id)
    zd_2= device_range_2[1]
    print(device_range_2[1])
    
    destination_id_3 = 0x6758
    range_step_mm = 1000         # distance that separates the amount of LEDs lighting up.
    device_range_3 = DeviceRange()
    status_3 = p.doRanging(destination_id_3, device_range_3, remote_id)
    zd_3= device_range_3[1]
    print(device_range_3[1])
    
    destination_id_4 = 0x6932      # network ID of the ranging destination
    range_step_mm = 1000         # distance that separates the amount of LEDs lighting up.
    device_range_4 = DeviceRange()
    status_4 = p.doRanging(destination_id_4, device_range_4, remote_id)
    zd_4= device_range_4[1]
    print(device_range_4[1])
    
    
    #H = np.matrix([[7.54,0],[7.54,7.21],[14.14,0],[14.14,7.58]])
    zd_nlos = np.matrix([zd_1,zd_2,zd_3,zd_4])
    #z_meas = zd_nlos
    #print(zd_nlos)
    
    dt = 1

    H = np.array([[0,6.78],[6.42,7.20],[5.4,15.52],[0,15.26]])
    H2 = np.matrix([[0,6.78],[6.42,7.20],[5.4,15.52],[0,15.26]])    
    
    
    zd = np.matrix([zd_1,zd_2,zd_3,zd_4])
    z_meas = zd*10**(-3)
    #z_meas = np.matrix([4.8,2.41,8.16088231,7.161592])
    #print(x_0)
        
    x_nlos = tri(zd_nlos*10**(-3),H2)
    x_nlos = x_nlos.T+H[0]
    print(x_nlos)
#    write_ws['A1'] = 'x'
#    write_ws['B1'] = 'y'
#    write_ws.cell(i+1,1,x_nlos[(0,0)])
#    write_ws.cell(i+1,2,x_nlos[(0,1)])
    write_ws.cell(j+1,1,x_nlos.item(0))
    write_ws.cell(j+1,2,x_nlos.item(1))
    #write_ws.cell(j+1,3,z_meas.item(2))
    #write_ws.cell(j+1,4,z_meas.item(3))
    #write_ws.cell(j+1,3,x_hat[0])
    #write_ws.cell(j+1,4,x_hat[1])
    write_wb.save('/Users/swbaek/Desktop/ranging_center_raw.xlsx')
    j = j+1

2092
5333
10096
10068
[[1.86487451 5.69700978]]
2074
5347
10072
10058
[[1.85776799 5.7147255 ]]
2083
5323
10030
10068
[[1.89956337 5.72236767]]
2083
5337
10058
10021
[[1.85281021 5.74827553]]
2050
5291
10016
10025
[[1.89544268 5.74906409]]
2088
5323
0
0
[[ 1.51777838 11.70753446]]
0
5366
10049
9927
[[1.55051397 5.65054411]]
2055
5398
10063
9847
[[1.71390956 5.88290361]]
2069
5389
10058
9842
[[1.72246234 5.88936904]]
2111
5520
9927
9275
[[1.42049423 6.38584424]]
2088
5323
9824
9078
[[1.49091893 6.52258919]]
1910
5305
9730
8707
[[1.3298798  6.77722575]]
1910
5698
9655
9059
[[1.27625434 6.65333543]]
1961
5403
9584
8290
[[1.15568743 7.13140487]]
1849
5642
9514
8149
[[0.94676256 7.27806796]]
1919
5122
9444
8055
[[1.27903645 7.27255434]]
1933
5417
9387
0
[[-0.59976087  9.7871636 ]]
1938
5450
9397
8407
[[1.25434357 7.14088646]]
1938
5183
9275
8501
[[1.51516339 7.07891755]]
1853
5094
9045
8412
[[1.60780599 7.19694143]]
1643
5019
8853
7976
[[1.50092391 7.49550632]]
1521
4930
8979
7901
[[1.44830

0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]

0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]
0
0
0
0
[[ 2.93743671 11.01157008]]


SerialException: [Errno 2] could not open port /dev/cu.usbmodem328B345A30371: [Errno 2] No such file or directory: '/dev/cu.usbmodem328B345A30371'

In [ ]:
pip install pypozyx

In [ ]:
pip install pyserial

In [ ]:
print(z_meas.item(0))