In [39]:
import numpy as np

def h(x,H):
    d = x-H
    d = np.multiply(d,d)
    d = np.sqrt(d.sum(axis=1))
    d_col_1 = d[1]-d[0]
    d_col_2 = d[2]-d[0] 
    d_col_3 = d[3]-d[0]
    di = np.array([d_col_1,d_col_2,d_col_3])
    di = di.T
    return di

class UGMM(object):
    '''Univariate GMM with CAVI'''
    def __init__(self, X, K=2, sigma=1):
        self.X = X
        self.K = K
        self.N = self.X.shape[0]
        self.sigma2 = sigma**2

    def _init(self):
        self.phi = np.random.dirichlet([np.random.random()*np.random.randint(1, 10)]*self.K, self.N)
        print(self.phi)
        K = X[0]
        K = np.append(K,X[SAMPLE])
        K = np.append(K,X[2*SAMPLE])
        K = np.append(K,X[3*SAMPLE])
        print(K)
        self.m = K
        self.s2 = np.ones(self.K) * np.random.random(self.K)
        print('Init mean')
        print(self.m)
        print('Init s2')
        print(self.s2)

    def get_elbo(self):
        t1 = np.log(self.s2) - self.m/self.sigma2
        t1 = t1.sum()
        t2 = -0.5*np.add.outer(self.X**2, self.s2+self.m**2)
        t2 += np.outer(self.X, self.m)
        t2 -= np.log(self.phi)
        t2 *= self.phi
        t2 = t2.sum()
        return t1 + t2

    def fit(self, max_iter=100, tol=1e-10):
        self._init()
        self.elbo_values = [self.get_elbo()]
        self.m_history = [self.m]
        self.s2_history = [self.s2]
        for iter_ in range(1, max_iter+1):
            self._cavi()
            self.m_history.append(self.m)
            self.s2_history.append(self.s2)
            self.elbo_values.append(self.get_elbo())
            if iter_ % 5 == 0:
                print(iter_, self.m_history[iter_])
            if np.abs(self.elbo_values[-2] - self.elbo_values[-1]) <= tol:
                print('ELBO converged with ll %.3f at iteration %d'%(self.elbo_values[-1],
                                                                     iter_))
                break

        if iter_ == max_iter:
            print('ELBO ended with ll %.3f'%(self.elbo_values[-1]))
            print(self.elbo_values)

    def _cavi(self):
        self._update_phi()
        self._update_mu()

    def _update_phi(self):
        t1 = np.outer(self.X, self.m)
        t2 = -(0.5*self.m**2 + 0.5*self.s2)
        exponent = t1 + t2[np.newaxis, :]
        self.phi = np.exp(exponent)
        self.phi = self.phi / self.phi.sum(1)[:, np.newaxis]

    def _update_mu(self):
        self.m = (self.phi*self.X[:, np.newaxis]).sum(0) * (1/self.sigma2 + self.phi.sum(0))**(-1)
        assert self.m.size == self.K
        self.s2 = (1/self.sigma2 + self.phi.sum(0))**(-1)
        assert self.s2.size == self.K

import os
import psutil

def _check_usage_of_cpu_and_memory():
    
    pid = os.getpid()
    py  = psutil.Process(pid)
    
    cpu_usage   = os.popen("ps aux | grep " + str(pid) + " | grep -v grep | awk '{print $3}'").read()
    cpu_usage   = cpu_usage.replace("\n","")
    
    memory_usage  = round(py.memory_info()[0] /2.**30, 2)
    
    print("cpu usage\t\t:", cpu_usage, "%")
    print("memory usage\t\t:", memory_usage, "%")
        
        
def tri(zd, H):
    zd = zd.T
    H=H-H[0]
    tmp = zd[0]
    tmp = tmp * tmp
    zd = np.delete(zd,(0), axis=0)
    r1=np.multiply(zd,zd)
    Ha=np.delete(H,(0), axis=0)
    K=np.multiply(Ha,Ha)
    K=K.sum(axis=1)
    b= 0.5*(K-r1+tmp) 
    S_inv = np.linalg.inv(Ha.T*Ha)*Ha.T
    x_hat = S_inv*b
    return x_hat

import matplotlib.pyplot as plt
import seaborn as sns

from openpyxl import Workbook
write_wb = Workbook()
std = 0.5
###########################################################################################################
# Ranging #
from pypozyx import *
import numpy as np
from pypozyx.definitions.registers import *
import sys
import time
import serial 
from openpyxl import Workbook
write_wb = Workbook()
write_ws = write_wb.active

i = 1    
port = get_first_pozyx_serial_port()#'/dev/cu.usbmodem3998326833361'
p = PozyxSerial(port)

remote_id = 0x696a          # the network ID of the remote device
remote = False               # whether to use the given remote device for ranging
if not remote:
    remote_id = None
while True:
    #ser = serial.Serial(port=port,baudrate=28800, timeout = 1)
    #print ser
    destination_id_1 = 0x6758      # network ID of the ranging destination
    range_step_mm = 1000         # distance that separates the amount of LEDs lighting up.
    device_range_1 = DeviceRange()
    status_1 = p.doRanging(destination_id_1, device_range_1, remote_id)
    zd_1= device_range_1[1]
    print(device_range_1[1])
    
    destination_id_2 = 0x6714      # network ID of the ranging destination
    range_step_mm = 1000         # distance that separates the amount of LEDs lighting up.
    device_range_2 = DeviceRange()
    status_2 = p.doRanging(destination_id_2, device_range_2, remote_id)
    zd_2= device_range_2[1]
    print(device_range_2[1])
    
    destination_id_3 = 0x6a5e
    range_step_mm = 1000         # distance that separates the amount of LEDs lighting up.
    device_range_3 = DeviceRange()
    status_3 = p.doRanging(destination_id_3, device_range_3, remote_id)
    zd_3= device_range_3[1]
    print(device_range_3[1])
    
    destination_id_4 = 0x6e6e      # network ID of the ranging destination
    range_step_mm = 1000         # distance that separates the amount of LEDs lighting up.
    device_range_4 = DeviceRange()
    status_4 = p.doRanging(destination_id_4, device_range_4, remote_id)
    zd_4= device_range_4[1]
    print(device_range_4[1])
    zd = np.array([[device_range_1[1]*10**(-3),device_range_2[1]*10**(-3),device_range_3[1]*10**(-3),device_range_4[1]*10**(-3)]])
    SAMPLE = 1000
    X1 = np.random.normal(loc= float(zd[0][0]), scale=std, size=SAMPLE)
    X2 = np.random.normal(loc= float(zd[0][1]), scale=std, size=SAMPLE)
    X3 = np.random.normal(loc= float(zd[0][2]), scale=std, size=SAMPLE)
    X4 = np.random.normal(loc= float(zd[0][3]), scale=std, size=SAMPLE)
    X1 = X1.T
    X2 = X2.T
    X3 = X3.T
    X4 = X4.T
    X = np.append(X1,X2)
    X = np.append(X,X3)
    X = np.append(X,X4)
    ugmm = UGMM(X, 4)
    ugmm.fit()
    ugmm.phi.argmax(1)
    zd_5 = np.matrix([ugmm.m[0],ugmm.m[1],ugmm.m[2],ugmm.m[3]])
    H = np.matrix([[7.54,0],[7.54,7.21],[14.14,0],[14.14,7.58]])
    #zd = np.matrix([zd_1,zd_2,zd_3,zd_4])
    #print(zd_nlos)
    x_vi = tri(zd_5*10**(-3),H)
    x_vi = x_vi.T+H[0]
    print(x_vi)
    x_hat = tri(zd,H)
    x_hat = x_hat.T+H[0]
    print(x_hat)
    write_ws['A1'] = 'Real'
    #write_ws['C1'] = 'VI'
    write_ws.cell(i+1,1,zd_1)
    write_ws.cell(i+1,2,zd_2)
    write_ws.cell(i+1,3,zd_3)
    write_ws.cell(i+1,4,zd_4)
    write_wb.save('/Users/swbaek/Desktop/vi.xlsx')
    i = i+1

3745
5084
5356
6181
[[0.17010636 0.27644772 0.20163537 0.35181055]
 [0.23821349 0.32345664 0.20452072 0.23380915]
 [0.34455355 0.08287186 0.38101997 0.19155463]
 ...
 [0.26097112 0.44384719 0.19922887 0.09595282]
 [0.26007064 0.28856833 0.26985441 0.18150663]
 [0.3429352  0.28634508 0.18740726 0.18331246]]
[3.74731269 5.12401799 5.14024518 5.8337059 ]
Init mean
[3.74731269 5.12401799 5.14024518 5.8337059 ]
Init s2
[0.76794968 0.94714518 0.49660831 0.56296491]
5 [4.42686848 5.22774991 5.23477583 5.4227881 ]
10 [4.53087171 5.23043808 5.23441847 5.32638325]
15 [4.57313635 5.23126043 5.23371203 5.28616473]
20 [4.59496559 5.23168882 5.23325172 5.26521845]
25 [4.6074991  5.23194836 5.23296245 5.25313529]
30 [4.61511361 5.23211547 5.23278011 5.24576964]
35 [4.61989467 5.23222626 5.2326645  5.2411321 ]
40 [4.62295791 5.23230085 5.23259091 5.23815363]
45 [4.62494572 5.23235149 5.23254394 5.23621651]
50 [4.62624629 5.23238605 5.23251393 5.23494644]
55 [4.62710177 5.23240969 5.23249476 5.23410932

30 [4.70383824 5.14905178 5.04568815 5.1482254 ]
35 [4.71525381 5.14201054 5.04834371 5.1412893 ]
40 [4.72374678 5.13650276 5.05084683 5.13586516]
45 [4.73020383 5.13207468 5.05322344 5.13150552]
50 [4.73518895 5.12843694 5.05549047 5.12792508]
55 [4.73907975 5.12539562 5.05765925 5.12493253]
60 [4.74213948 5.12281549 5.0597375  5.12239453]
65 [4.74455761 5.12059924 5.06173055 5.12021508]
70 [4.74647418 5.11867502 5.0636422  5.11832332]
75 [4.74799484 5.1169886  5.06547524 5.11666575]
80 [4.74920073 5.11549832 5.06723184 5.11520129]
85 [4.75015506 5.11417167 5.0689138  5.11389787]
90 [4.75090759 5.11298295 5.07052272 5.11273015]
95 [4.75149789 5.11191157 5.07206012 5.11167784]
100 [4.75195766 5.11094092 5.07352751 5.11072455]
ELBO ended with ll 3468.380
[-1751.8632170883548, 3176.110373157494, 3383.6548638227205, 3434.7236645316607, 3450.774936480801, 3457.6697269888555, 3461.2710029823943, 3463.3766218819987, 3464.7052146660503, 3465.5919084636257, 3466.2098442274423, 3466.65555395186

5070
5380
6185
[[0.52112068 0.26784851 0.07841353 0.13261727]
 [0.04412635 0.06077758 0.70658982 0.18850624]
 [0.14048682 0.14226481 0.09353535 0.62371301]
 ...
 [0.3116735  0.13564052 0.21250365 0.34018234]
 [0.23723086 0.40669318 0.22429504 0.13178091]
 [0.70951606 0.00359316 0.16188248 0.12500831]]
[3.26276182 5.44498521 4.83006628 6.28929281]
Init mean
[3.26276182 5.44498521 4.83006628 6.28929281]
Init s2
[0.69485397 0.03679008 0.0264639  0.65102213]
5 [4.43440175 5.31895158 5.12463135 5.45752656]
10 [4.5659457  5.27740976 5.16812777 5.33843288]
15 [4.61706803 5.25682255 5.18804035 5.29043483]
20 [4.64400004 5.2447166  5.19947044 5.26509081]
25 [4.66022681 5.23698216 5.20652944 5.24998878]
30 [4.67076197 5.23181068 5.21103233 5.2403786 ]
35 [4.67792361 5.22825482 5.21395058 5.23401438]
40 [4.68293957 5.22576408 5.21585622 5.22968893]
45 [4.68652392 5.22399664 5.21710391 5.22669653]
50 [4.68912083 5.22273059 5.21792016 5.2246002 ]
55 [4.69102053 5.22181731 5.21845218 5.22311809]
60 

10 [4.61556075 5.01481266 5.17921127 5.39850549]
15 [4.64123298 5.04341966 5.18553038 5.33878153]
20 [4.6492162  5.06521935 5.19033127 5.30454162]
25 [4.6499258  5.08370593 5.19398688 5.28183964]
30 [4.64746539 5.09997995 5.19665479 5.26541881]
35 [4.64379124 5.11441558 5.19847417 5.25285326]
40 [4.63990387 5.12715077 5.19959398 5.24287764]
45 [4.636303   5.13826657 5.20016646 5.23477135]
50 [4.63320525 5.14785307 5.20033484 5.22809168]
55 [4.63066664 5.15602659 5.20022376 5.22254568]
60 [4.62865756 5.16292581 5.19993451 5.21792505]
65 [4.62710891 5.168701   5.19954456 5.21407191]
70 [4.62593946 5.17350309 5.19910991 5.21086061]
75 [4.62507071 5.17747538 5.19866876 5.20818786]
80 [4.62443386 5.18074835 5.1982455  5.20596712]
85 [4.62397206 5.18343731 5.19785431 5.20412526]
90 [4.62364022 5.18564184 5.19750225 5.20260031]
95 [4.62340356 5.18744654 5.19719156 5.2013398 ]
100 [4.62323588 5.18892245 5.19692145 5.20029941]
ELBO ended with ll 3429.150
[-2547.4775360018207, 3092.465981814223,

50 [4.59818785 5.15779918 5.14170158 5.17390669]
55 [4.59823913 5.15786469 5.14473458 5.1707609 ]
60 [4.59821156 5.15791214 5.14721985 5.16825733]
65 [4.5981535  5.15794385 5.14924895 5.16625492]
70 [4.59808929 5.15796315 5.15090084 5.16464773]
75 [4.59803009 5.15797329 5.15224264 5.16335456]
80 [4.5979801  5.15797706 5.1533307  5.16231224]
85 [4.59794003 5.15797665 5.15421187 5.16147111]
90 [4.59790898 5.15797368 5.15492484 5.16079179]
95 [4.59788552 5.15796933 5.15550132 5.16024284]
100 [4.59786809 5.15796437 5.15596722 5.15979909]
ELBO ended with ll 3435.409
[802.4432310446491, 3357.274020053342, 3410.5122806379127, 3422.0361560227434, 3427.327029503692, 3430.1418574746713, 3431.783756056422, 3432.8082080435274, 3433.4811301848836, 3433.9414091465173, 3434.2667265368746, 3434.5029832781142, 3434.6785460435535, 3434.8116114126647, 3434.9142250381997, 3434.9945779245786, 3435.058370621255, 3435.1096514681, 3435.1513470311297, 3435.1856065457414, 3435.2140307616605, 3435.237827117747, 

6190
[[9.80734326e-01 1.03326869e-02 6.73950767e-03 2.19347900e-03]
 [4.91726765e-01 6.87877919e-04 5.07585357e-01 1.20846930e-10]
 [9.29229304e-01 2.49903902e-06 1.09995827e-09 7.07681960e-02]
 ...
 [8.92308063e-01 9.11589101e-05 1.07597328e-01 3.45001964e-06]
 [2.48324159e-04 5.36348758e-05 9.99698039e-01 2.06014346e-09]
 [7.65612558e-01 2.32742681e-05 2.34363751e-01 4.17540565e-07]]
[ 4.21260755  5.10164922 -0.47814545  6.77566906]
Init mean
[ 4.21260755  5.10164922 -0.47814545  6.77566906]
Init s2
[0.26035457 0.50804391 0.5329036  0.16593761]
5 [4.27610796 4.94802051 0.00969828 5.70892029]
10 [4.2815595  4.98668127 0.01027109 5.66714967]
15 [4.26757856 5.02042025 0.01022688 5.64988379]
20 [4.25383321 5.05088351 0.0101206  5.63517862]
25 [4.24230067 5.07820066 0.01002414 5.6211504 ]
30 [4.23284706 5.10254799 0.00994386 5.60778702]
35 [4.22511142 5.12420516 0.00987802 5.59518991]
40 [4.21875637 5.14348737 0.00982406 5.58340477]
45 [4.21350267 5.16070224 0.00977967 5.57242763]
50 [4.2

3708
0
5187
6213
[[0.4761108  0.2510738  0.17981849 0.09299691]
 [0.59261029 0.05629065 0.08614677 0.26495229]
 [0.06448463 0.16618704 0.40995431 0.35937402]
 ...
 [0.22660177 0.22004649 0.30146441 0.25188733]
 [0.13740093 0.33541186 0.49262035 0.03456686]
 [0.45152179 0.17223457 0.11366656 0.26257708]]
[ 3.4472282  -0.61280593  5.36271949  5.79124755]
Init mean
[ 3.4472282  -0.61280593  5.36271949  5.79124755]
Init s2
[0.92035198 0.0642368  0.13142715 0.34393558]
5 [4.09395744 0.03689119 5.37664065 5.59481866]
10 [4.1173628  0.03802194 5.41098912 5.55036752]
15 [4.1165146  0.03805201 5.43605616 5.52719772]
20 [4.11543088 0.03803797 5.45249301 5.51213579]
25 [4.1149162  0.03803005 5.46312074 5.50213675]
30 [4.11469264 0.03802653 5.47000574 5.49552339]
35 [4.11459684 0.03802502 5.47447881 5.49116664]
40 [4.11455586 0.03802437 5.47739112 5.48830408]
45 [4.11453834 0.03802409 5.47929004 5.48642643]
50 [4.11453085 0.03802398 5.48052943 5.48519614]
55 [4.11452765 0.03802392 5.48133888 5.484

5 [4.17218511 0.03167242 5.15394186 5.63624267]
10 [4.19443129 0.0329423  5.21729354 5.56714102]
15 [4.18456932 0.03291701 5.26652672 5.53055575]
20 [4.17673155 0.03283742 5.30358117 5.50269559]
25 [4.17210166 0.03278591 5.33094711 5.48071841]
30 [4.16949026 0.0327565  5.35111454 5.46359441]
35 [4.16802727 0.03274002 5.36600755 5.45040968]
40 [4.16720751 0.03273081 5.37703568 5.44034003]
45 [4.16674773 0.03272564 5.38522264 5.43269109]
50 [4.16648965 0.03272275 5.3913134  5.42690246]
55 [4.16634472 0.03272112 5.39585252 5.42253306]
60 [4.16626331 0.03272021 5.39923991 5.41924101]
65 [4.16621758 0.0327197  5.4017705  5.41676399]
70 [4.16619188 0.03271941 5.40366256 5.41490203]
75 [4.16617744 0.03271925 5.4050781  5.4135034 ]
80 [4.16616933 0.03271916 5.40613764 5.41245337]
85 [4.16616477 0.03271911 5.406931   5.41166535]
90 [4.16616221 0.03271908 5.40752521 5.41107413]
95 [4.16616077 0.03271906 5.40797036 5.41063067]
100 [4.16615996 0.03271905 5.40830389 5.41029809]
ELBO ended with ll 1

5061
5309
6152
[[0.13970081 0.20940207 0.5218309  0.12906622]
 [0.30677498 0.11211508 0.2672257  0.31388424]
 [0.44082672 0.08604212 0.12933856 0.34379259]
 ...
 [0.46230758 0.17908769 0.11737497 0.24122976]
 [0.31252763 0.19896547 0.21715905 0.27134784]
 [0.21583168 0.61265022 0.06962233 0.10189577]]
[4.7191276  4.23979016 4.32522004 6.58124199]
Init mean
[4.7191276  4.23979016 4.32522004 6.58124199]
Init s2
[0.17148111 0.32189337 0.32228617 0.80715873]
5 [5.0857671  4.79392201 4.85274336 5.47805348]
10 [5.1090278  4.85732307 4.91333626 5.33045975]
15 [5.11540524 4.88825104 4.94377093 5.26298366]
20 [5.11634917 4.90803682 4.96359503 5.22258541]
25 [5.11500453 4.92242923 4.97809916 5.19512871]
30 [5.11260642 4.93370915 4.9893991  5.17500961]
35 [5.10973044 4.9429889  4.99854025 5.15950842]
40 [5.10667083 4.95088617 5.00611477 5.14712816]
45 [5.10358568 4.95777591 5.01249237 5.13697009]
50 [5.10056165 4.96390076 5.01792138 5.12845896]
55 [5.09764581 4.96942546 5.02257837 5.12120796]
60 

30 [ 4.78939347e+00  4.99858162e+00 -3.01934570e-03  5.20595939e+00]
35 [ 4.80045533e+00  4.99810296e+00 -2.97061224e-03  5.19547577e+00]
40 [ 4.80912222e+00  4.99768098e+00 -2.93437842e-03  5.18730458e+00]
45 [ 4.81608734e+00  4.99729940e+00 -2.90651241e-03  5.18077756e+00]
50 [ 4.82179579e+00  4.99694752e+00 -2.88451938e-03  5.17546548e+00]
55 [ 4.82654792e+00  4.99661801e+00 -2.86680380e-03  5.17107865e+00]
60 [ 4.83055448e+00  4.99630565e+00 -2.85229764e-03  5.16741370e+00]
65 [ 4.83396822e+00  4.99600664e+00 -2.84025897e-03  5.16432320e+00]
70 [ 4.83690284e+00  4.99571813e+00 -2.83015626e-03  5.16169741e+00]
75 [ 4.83944483e+00  4.99543798e+00 -2.82159868e-03  5.15945276e+00]
80 [ 4.84166135e+00  4.99516449e+00 -2.81429239e-03  5.15752440e+00]
85 [ 4.84360533e+00  4.99489636e+00 -2.80801224e-03  5.15586114e+00]
90 [ 4.84531914e+00  4.99463256e+00 -2.80258272e-03  5.15442201e+00]
95 [ 4.84683711e+00  4.99437224e+00 -2.79786505e-03  5.15317380e+00]
100 [ 4.84818737e+00  4.99411475e+

3994
4888
5267
6040
[[0.18658221 0.42027707 0.15436191 0.23877881]
 [0.31773712 0.07913033 0.52839528 0.07473728]
 [0.18127593 0.1190625  0.24779994 0.45186163]
 ...
 [0.35531783 0.3654337  0.07936102 0.19988745]
 [0.68499675 0.19347547 0.01354126 0.10798652]
 [0.24737996 0.01254232 0.19480872 0.545269  ]]
[4.2020726  4.72015924 5.54995523 6.40940341]
Init mean
[4.2020726  4.72015924 5.54995523 6.40940341]
Init s2
[0.72133403 0.4856162  0.08540306 0.96907923]
5 [4.8483795  4.95070315 5.12346454 5.2698894 ]
10 [4.98125371 5.01561565 5.0737344  5.12203244]
15 [5.02486863 5.03685817 5.05710482 5.07385674]
20 [5.04002274 5.04421953 5.05130081 5.0571525 ]
25 [5.04532182 5.04679078 5.04926859 5.05131532]
30 [5.04717604 5.04769013 5.04855717 5.04927328]
35 [5.04782489 5.04800479 5.04830819 5.04855876]
40 [5.04805194 5.04811489 5.04822106 5.04830874]
45 [5.04813139 5.04815342 5.04819057 5.04822125]
50 [5.04815919 5.0481669  5.0481799  5.04819064]
55 [5.04816892 5.04817162 5.04817617 5.04817993

5164
5679
[[0.1465412  0.32373875 0.31638842 0.21333163]
 [0.36152121 0.32605734 0.1644311  0.14799035]
 [0.15899829 0.28016932 0.25562954 0.30520285]
 ...
 [0.10105715 0.20900324 0.32088628 0.36905332]
 [0.30488963 0.34096145 0.16101313 0.19313579]
 [0.37278766 0.20458077 0.0842749  0.33835667]]
[3.88607304 4.62026093 5.30062339 5.85267843]
Init mean
[3.88607304 4.62026093 5.30062339 5.85267843]
Init s2
[0.90059314 0.74995879 0.28703666 0.73570264]
5 [4.87069954 4.90258938 4.93291748 4.95589565]
10 [4.91300072 4.91480783 4.91652337 4.91782084]
15 [4.91539456 4.91549687 4.915594   4.91566744]
20 [4.91553008 4.91553588 4.91554138 4.91554553]
25 [4.91553776 4.91553808 4.9155384  4.91553863]
ELBO converged with ll 4368.562 at iteration 27
[[10.90842232  3.67084767]]
[[10.18317591  3.33265877]]
4237
4733
0
5665
[[0.15679778 0.17112632 0.39594987 0.27612603]
 [0.34423901 0.1861669  0.29168391 0.17791018]
 [0.35811186 0.28290628 0.0590286  0.29995326]
 ...
 [0.37607195 0.23176098 0.23079363 

30 [4.92128482 4.92128454 4.92128521 4.92128518]
ELBO converged with ll 4266.571 at iteration 31
[[10.90842232  3.67084767]]
[[10.05075883  3.77761675]]
4490
4232
5534
5492
[[0.40403458 0.13269475 0.12473513 0.33853553]
 [0.13611269 0.59052913 0.19622206 0.07713612]
 [0.09728489 0.26489917 0.44159386 0.19622208]
 ...
 [0.26923183 0.29787174 0.28275035 0.15014609]
 [0.39350732 0.23280964 0.14461769 0.22906535]
 [0.22821709 0.20186851 0.32648934 0.24342505]]
[4.61319961 3.93754496 5.06419756 4.9583243 ]
Init mean
[4.61319961 3.93754496 5.06419756 4.9583243 ]
Init s2
[0.34834509 0.38451984 0.7871304  0.76420534]
5 [4.93165411 4.88705058 4.9616172  4.95473381]
10 [4.93362483 4.93028189 4.93586623 4.93535169]
15 [4.93376951 4.93351908 4.93393739 4.93389885]
20 [4.93378033 4.93376157 4.9337929  4.93379002]
25 [4.93378114 4.93377974 4.93378208 4.93378187]
ELBO converged with ll 4303.566 at iteration 28
[[10.90842232  3.67084767]]
[[10.06919681  3.78222852]]
0
4204
5604
5478
[[0.132176   0.405

4860
3853
5797
5169
[[0.42966595 0.11292372 0.32751286 0.12989747]
 [0.2038284  0.17634799 0.42626723 0.19355637]
 [0.41651943 0.10659396 0.15279352 0.3240931 ]
 ...
 [0.15595233 0.11451133 0.21948649 0.51004985]
 [0.16677475 0.17784077 0.43231182 0.22307266]
 [0.19551008 0.30558376 0.22279344 0.27611272]]
[5.36764427 4.04490658 4.8838592  5.1090351 ]
Init mean
[5.36764427 4.04490658 4.8838592  5.1090351 ]
Init s2
[0.18632852 0.65440457 0.13285927 0.77155229]
5 [5.0054279  4.73521337 4.92223253 4.96352759]
10 [4.93131755 4.86331991 4.911447   4.9214357 ]
15 [4.91300945 4.89589937 4.90807744 4.91056383]
20 [4.9084218  4.90412977 4.9071889  4.90781088]
25 [4.90727216 4.90619657 4.90696346 4.90711923]
30 [4.90698413 4.90671466 4.90690681 4.90694583]
35 [4.90691198 4.90684447 4.90689261 4.90690238]
40 [4.9068939  4.90687699 4.90688905 4.90689149]
45 [4.90688937 4.90688513 4.90688815 4.90688877]
50 [4.90688824 4.90688717 4.90688793 4.90688808]
ELBO converged with ll 3978.058 at iteration 50

5126
[[5.49938318e-02 6.29507996e-01 1.91962591e-01 1.23535581e-01]
 [8.30466348e-02 4.21295161e-01 4.94778262e-01 8.79942856e-04]
 [7.51698218e-01 1.24876645e-01 2.80629522e-02 9.53621852e-02]
 ...
 [7.22689048e-02 1.68345400e-01 2.28464157e-01 5.30921538e-01]
 [2.05265863e-02 7.71445666e-02 6.63214776e-01 2.39114071e-01]
 [1.61848452e-02 9.48231546e-01 2.56496556e-02 9.93395289e-03]]
[4.79896192 3.62814472 6.64426328 4.725536  ]
Init mean
[4.79896192 3.62814472 6.64426328 4.725536  ]
Init s2
[0.1342075  0.10159722 0.09544276 0.64173237]
5 [5.05912506 4.45296298 5.35904443 5.03252918]
10 [5.07246249 4.56413983 5.21627711 5.05642876]
15 [5.07309906 4.6186357  5.1564097  5.0626271 ]
20 [5.07052143 4.65425151 5.12324651 5.06339812]
25 [5.06694588 4.68070861 5.10216558 5.06196053]
30 [5.06311169 4.70181972 5.08753949 5.05954316]
35 [5.05930019 4.71945016 5.07672989 5.05669721]
40 [5.0556206  4.73464707 5.06834018 5.05369075]
45 [5.0521106  4.74805562 5.06156694 5.05065914]
50 [5.04877675 

5169
0
6227
4916
[[0.03062894 0.5417697  0.00519064 0.42241072]
 [0.77974643 0.10121503 0.09562104 0.02341749]
 [0.23446344 0.2790435  0.45583475 0.03065831]
 ...
 [0.02376278 0.17980312 0.69305555 0.10337855]
 [0.34093328 0.27216338 0.27118651 0.11571683]
 [0.48246598 0.01114696 0.1980564  0.30833067]]
[ 4.28978004 -0.62934413  5.98415666  5.71515134]
Init mean
[ 4.28978004 -0.62934413  5.98415666  5.71515134]
Init s2
[0.01015194 0.1343218  0.69257492 0.30567115]
5 [5.40646482 0.01033577 5.48224681 5.46713186]
10 [5.44916541 0.01034016 5.45385126 5.45290541]
15 [5.4517998  0.01034018 5.45209058 5.45203185]
20 [5.45196326 0.01034018 5.45198131 5.45197766]
25 [5.45197341 0.01034018 5.45197453 5.4519743 ]
ELBO converged with ll 2269.310 at iteration 27
[[10.90842156  3.670849  ]]
[[9.66612154 5.20721163]]
5272
3375
6331
4883
[[0.36874768 0.37726152 0.07434764 0.17964316]
 [0.30302981 0.31162252 0.25732764 0.12802003]
 [0.19721878 0.05489865 0.25399418 0.49388839]
 ...
 [0.50103541 0.0768

4808
[[0.37463724 0.19245186 0.17957001 0.25334088]
 [0.07267159 0.26936031 0.21496891 0.44299919]
 [0.23313186 0.20637875 0.49956254 0.06092685]
 ...
 [0.18714883 0.29296278 0.0519934  0.46789499]
 [0.07616654 0.18884671 0.09150063 0.64348611]
 [0.21738704 0.15313093 0.19579568 0.43368634]]
[5.50954516 2.79927081 6.47712551 4.43028081]
Init mean
[5.50954516 2.79927081 6.47712551 4.43028081]
Init s2
[0.2185106  0.72729535 0.57468773 0.21767641]
5 [5.64182161 3.74924037 5.90044567 4.8011549 ]
10 [5.70669747 3.73203044 5.8121787  4.89926333]
15 [5.72046818 3.71254799 5.76790076 4.97064548]
20 [5.71774031 3.69972107 5.74078455 5.02936904]
25 [5.70936079 3.69069568 5.72131511 5.07894424]
30 [5.69917532 3.68405659 5.70573448 5.12157624]
35 [5.68863353 3.67901281 5.69241099 5.15883678]
40 [5.67828968 3.67508188 5.68055896 5.19186883]
45 [5.66834545 3.67195499 5.66976033 5.22150859]
50 [5.65886083 3.66942718 5.6597726  5.24837124]
55 [5.6498403  3.66735798 5.65044548 5.27291206]
60 [5.6412689

30 [5.94083908 3.41723564 5.94182554 5.78346655]
35 [5.92377835 3.41774331 5.92429585 5.82235866]
40 [5.91196072 3.41797303 5.91224667 5.84807799]
45 [5.90416458 3.41806942 5.904328   5.8645464 ]
50 [5.89918691 3.41810784 5.8992823  5.87486445]
55 [5.89607536 3.41812265 5.89613178 5.88123875]
60 [5.89415618 3.41812824 5.89418982 5.88514193]
65 [5.89298224 3.41813032 5.8930024  5.88751888]
70 [5.8922678  3.41813109 5.89227992 5.88896153]
75 [5.89183437 3.41813137 5.89184167 5.88983532]
80 [5.89157191 3.41813147 5.89157631 5.89036391]
85 [5.89141317 3.41813151 5.89141582 5.89068343]
90 [5.89131722 3.41813153 5.89131882 5.89087648]
95 [5.89125925 3.41813153 5.89126021 5.89099309]
100 [5.89122423 3.41813153 5.89122482 5.89106351]
ELBO ended with ll 2272.119
[-5272.870186605905, 2031.3101191454648, 2232.8995666195556, 2249.6894807172152, 2254.643933700181, 2257.3690845664137, 2259.152158743779, 2260.452894066057, 2261.4945064589206, 2262.389834388331, 2263.196102161711, 2263.9421180065387, 

<ipython-input-39-43c12fbc70fe>:76: RuntimeWarning: overflow encountered in exp
  self.phi = np.exp(exponent)
<ipython-input-39-43c12fbc70fe>:77: RuntimeWarning: invalid value encountered in true_divide
  self.phi = self.phi / self.phi.sum(1)[:, np.newaxis]
<ipython-input-39-43c12fbc70fe>:42: RuntimeWarning: divide by zero encountered in log
  t2 -= np.log(self.phi)


6181
2963
6701
4752
[[0.2150909  0.27436783 0.11172526 0.39881601]
 [0.20979062 0.20845053 0.20518237 0.37657648]
 [0.09063928 0.6406799  0.10684339 0.16183743]
 ...
 [0.19870001 0.26881609 0.33422086 0.19826304]
 [0.37541182 0.16050757 0.26800291 0.1960777 ]
 [0.3526801  0.09463631 0.45964011 0.09304348]]
[6.24473211 3.73247874 7.53124697 5.24209163]
Init mean
[6.24473211 3.73247874 7.53124697 5.24209163]
Init s2
[0.89654655 0.19165755 0.1549922  0.10317554]
5 [6.08221511 3.24137951 6.21491602 5.41864803]
10 [6.08865586 3.24343442 6.12851676 5.55651006]
15 [6.06539158 3.24940985 6.08011294 5.66770587]
20 [6.03754373 3.25322343 6.04391365 5.75393294]
25 [6.01295254 3.25539952 6.01605299 5.81801985]
30 [5.99371846 3.25652536 5.99535882 5.86364038]
35 [5.97975868 3.25706163 5.98067739 5.89489519]
40 [5.97013588 3.25730103 5.97067022 5.91566436]
45 [5.96373465 3.25740292 5.96405315 5.92916009]
50 [5.95957748 3.25744486 5.95977032 5.93779469]
55 [5.95691999 3.25746174 5.95703792 5.94326242

80 [6.25679229 3.1802574  6.25679229 4.12793333]
85 [6.25663472 3.18115298 6.25663472 4.12540959]
90 [6.25651172 3.18185636 6.25651172 4.12343957]
95 [6.25641559 3.18240868 6.25641559 4.12190001]
100 [6.25634041 3.18284233 6.25634041 4.12069574]
ELBO ended with ll 1838.367
[-5493.284744157058, 1797.4264753886712, 1824.7379883082235, 1826.6600351683942, 1828.1644180794783, 1829.4396692239786, 1830.542038236745, 1831.5033923157134, 1832.3469645594228, 1833.0904475876998, 1833.7475064505848, 1834.3289376845034, 1834.8435398983434, 1835.2987198090163, 1835.7008896545335, 1836.0557172640658, 1836.368279768409, 1836.6431580224007, 1836.8844965370279, 1837.0960444919228, 1837.2811870545174, 1837.4429721306678, 1837.5841351555098, 1837.707123069089, 1837.8141178230767, 1837.9070593706097, 1837.9876679311249, 1838.057465288917, 1838.117794914485, 1838.169840754094, 1838.2146445936555, 1838.2531219596997, 1838.2860765663042, 1838.3142133523697, 1838.33815017927, 1838.3584282751199, 1838.37552152

7123
4433
[[0.0944989  0.18872339 0.42915217 0.28762553]
 [0.13757636 0.10278023 0.45957333 0.30007008]
 [0.25869175 0.21870695 0.1290946  0.3935067 ]
 ...
 [0.29046317 0.11479227 0.48298542 0.11175915]
 [0.42895106 0.12843758 0.16011278 0.28249858]
 [0.33228543 0.21551042 0.15667346 0.29553069]]
[6.93270983 2.58307777 7.00509197 4.17839293]
Init mean
[6.93270983 2.58307777 7.00509197 4.17839293]
Init s2
[0.02481195 0.06878539 0.15490768 0.05532912]
5 [6.69481327 3.15196761 6.69951918 3.93007513]
10 [6.68508958 3.2498035  6.68549829 3.77143313]
15 [6.68087844 3.31327056 6.68091607 3.68834406]
20 [6.67891605 3.35699079 6.6789196  3.63609476]
25 [6.67789963 3.3886511  6.67789997 3.60011814]
30 [6.67733915 3.41229133 6.67733919 3.57412105]
35 [6.67701866 3.43025822 6.67701866 3.55481312]
40 [6.67683147 3.44405152 6.67683147 3.54023875]
45 [6.67672078 3.45470073 6.67672078 3.52912839]
50 [6.67665484 3.46294804 6.67665484 3.52060663]
55 [6.67661538 3.46934564 6.67661538 3.51404491]
60 [6.67

2198683648
2650
7367
4410
[[8.71514744e-04 9.99085933e-01 4.25526733e-05 4.49923859e-57]
 [9.93002305e-01 1.79411238e-33 6.99769541e-03 4.50934773e-34]
 [2.35929580e-15 9.99984281e-01 1.57192674e-05 1.07349055e-44]
 ...
 [9.99999999e-01 1.11100152e-09 1.05187343e-12 5.02150784e-32]
 [1.57857044e-04 2.79446326e-55 1.77561751e-06 9.99840367e-01]
 [4.36496062e-87 2.19609752e-03 9.97803902e-01 3.21609915e-30]]
[2.19868360e+06 2.53732491e+00 7.47439614e+00 5.59542848e+00]
Init mean
[2.19868360e+06 2.53732491e+00 7.47439614e+00 5.59542848e+00]
Init s2
[0.00426271 0.44694553 0.14599531 0.62520034]
5 [nan nan nan nan]
10 [nan nan nan nan]
15 [nan nan nan nan]
20 [nan nan nan nan]
25 [nan nan nan nan]
30 [nan nan nan nan]
35 [nan nan nan nan]
40 [nan nan nan nan]
45 [nan nan nan nan]
50 [nan nan nan nan]
55 [nan nan nan nan]
60 [nan nan nan nan]
65 [nan nan nan nan]
70 [nan nan nan nan]
75 [nan nan nan nan]
80 [nan nan nan nan]
85 [nan nan nan nan]
90 [nan nan nan nan]
95 [nan nan nan nan]
100 

<ipython-input-39-43c12fbc70fe>:43: RuntimeWarning: invalid value encountered in multiply
  t2 *= self.phi


25 [8.01679216 3.02841851 8.01678593 3.95458964]
30 [8.01677994 3.02868283 8.01677943 3.95429585]
35 [8.01677668 3.02876827 8.01677664 3.95420092]
40 [8.01677569 3.0287959  8.01677568 3.95417021]
45 [8.01677537 3.02880483 8.01677537 3.95416028]
50 [8.01677527 3.02880773 8.01677527 3.95415706]
55 [8.01677523 3.02880866 8.01677523 3.95415602]
60 [8.01677522 3.02880897 8.01677522 3.95415569]
65 [8.01677522 3.02880906 8.01677522 3.95415558]
70 [8.01677522 3.0288091  8.01677522 3.95415554]
75 [8.01677522 3.02880911 8.01677522 3.95415553]
80 [8.01677522 3.02880911 8.01677522 3.95415553]
85 [8.01677522 3.02880911 8.01677522 3.95415553]
ELBO converged with ll 1075.385 at iteration 89
[[10.9084221   3.67085127]]
[[11.43218285  7.53039187]]
7381
2575
7559
4344
[[0.53128747 0.03386466 0.13408716 0.30076072]
 [0.09853676 0.51183628 0.14486045 0.24476651]
 [0.39592675 0.19670728 0.30397465 0.10339132]
 ...
 [0.21793565 0.18048458 0.15132212 0.45025764]
 [0.16066942 0.25290576 0.4635277  0.12289711]

4293
[[0.1765207  0.31042943 0.31103688 0.20201299]
 [0.31581957 0.34158875 0.16323473 0.17935695]
 [0.20972772 0.24437047 0.24743444 0.29846736]
 ...
 [0.18313626 0.23514871 0.35675782 0.2249572 ]
 [0.34090943 0.18951068 0.26403945 0.20554044]
 [0.15921637 0.18764227 0.21484289 0.43829847]]
[6.40713578 3.68398677 7.75149468 4.03567496]
Init mean
[6.40713578 3.68398677 7.75149468 4.03567496]
Init s2
[0.37834479 0.74180083 0.50061035 0.81983534]
5 [7.53502608 3.45080743 7.58500846 3.56976722]
10 [7.55975319 3.48875377 7.56112769 3.53206041]
15 [7.56039679 3.50245861 7.56043462 3.51828336]
20 [7.56041183 3.50747348 7.56041287 3.51325878]
25 [7.56041189 3.50930791 7.56041192 3.51142306]
30 [7.56041184 3.50997874 7.56041184 3.51075206]
35 [7.56041183 3.51022402 7.56041183 3.51050676]
40 [7.56041183 3.5103137  7.56041183 3.51041707]
45 [7.56041183 3.51034649 7.56041183 3.51038428]
50 [7.56041183 3.51035848 7.56041183 3.5103723 ]
55 [7.56041183 3.51036286 7.56041183 3.51036791]
60 [7.5604118

30 [7.68172217 3.41543049 7.68172218 3.43356449]
35 [7.6817195  3.41963759 7.6817195  3.4293501 ]
40 [7.68171873 3.42189156 7.68171873 3.42709404]
45 [7.68171851 3.42309911 7.68171851 3.42588589]
50 [7.68171845 3.42374602 7.68171845 3.42523881]
55 [7.68171843 3.42409257 7.68171843 3.42489221]
60 [7.68171843 3.42427821 7.68171843 3.42470655]
65 [7.68171842 3.42437765 7.68171842 3.4246071 ]
70 [7.68171842 3.42443092 7.68171842 3.42455383]
75 [7.68171842 3.42445946 7.68171842 3.4245253 ]
80 [7.68171842 3.42447474 7.68171842 3.42451001]
85 [7.68171842 3.42448293 7.68171842 3.42450182]
90 [7.68171842 3.42448732 7.68171842 3.42449744]
95 [7.68171842 3.42448967 7.68171842 3.42449509]
100 [7.68171842 3.42449093 7.68171842 3.42449383]
ELBO converged with ll 1390.557 at iteration 100
ELBO ended with ll 1390.557
[-23387.131428017175, 1019.1822735460805, 1330.0101425992052, 1367.8128803622656, 1377.7495803655177, 1382.2762997686773, 1384.816977546244, 1386.4174536301648, 1387.5004819733388, 1388.2

4171
[[0.15832265 0.19251014 0.31147605 0.33769117]
 [0.22690817 0.21345638 0.36169994 0.19793551]
 [0.17868765 0.27265769 0.23502695 0.31362772]
 ...
 [0.09087232 0.42663687 0.25930691 0.22318391]
 [0.4139934  0.30893474 0.01855045 0.25852141]
 [0.29992175 0.11901708 0.1467045  0.43435668]]
[ 7.41956661  2.15079868 -1.07940564  3.76173135]
Init mean
[ 7.41956661  2.15079868 -1.07940564  3.76173135]
Init s2
[0.98695856 0.59113162 0.17729527 0.31210667]
5 [7.71962629 3.15577575 0.1371335  3.72764723]
10 [7.71944902 3.38687883 0.15807383 3.55297465]
15 [7.71929835 3.44605143 0.15926537 3.49638796]
20 [7.71928392 3.46367338 0.1593701  3.47899387]
25 [7.71928258 3.46901173 0.15937977 3.47367656]
30 [7.71928246 3.47063492 0.15938066 3.47205533]
35 [7.71928245 3.47112896 0.15938075 3.47156147]
40 [7.71928245 3.47127937 0.15938075 3.47141107]
45 [7.71928245 3.47132517 0.15938076 3.47136527]
50 [7.71928245 3.47133912 0.15938076 3.47135133]
55 [7.71928245 3.47134336 0.15938076 3.47134708]
ELBO 

65 [8.17304547 3.51681085 8.17304547 3.51683932]
70 [8.17304547 3.51681854 8.17304547 3.51683163]
75 [8.17304547 3.51682208 8.17304547 3.5168281 ]
80 [8.17304547 3.51682371 8.17304547 3.51682647]
ELBO converged with ll 1540.260 at iteration 81
[[10.90842225  3.67085138]]
[[10.09615252  7.37773652]]
8037
2696
8393
4330
[[0.25880951 0.2282126  0.38915206 0.12382583]
 [0.39995673 0.18100108 0.14612266 0.27291953]
 [0.26997194 0.11547009 0.20566342 0.40889455]
 ...
 [0.23269552 0.18910267 0.30625276 0.27194905]
 [0.24663027 0.12416904 0.13839278 0.49080792]
 [0.42740316 0.27723496 0.17834771 0.11701417]]
[8.27991563 1.932927   8.86795457 4.49241284]
Init mean
[8.27991563 1.932927   8.86795457 4.49241284]
Init s2
[0.00426017 0.17362426 0.22726636 0.49599169]
5 [8.18942308 3.19441384 8.19126803 3.79320652]
10 [8.18926811 3.32814338 8.18927509 3.65746515]
15 [8.18898343 3.39221937 8.18898346 3.59287606]
20 [8.18888131 3.42933294 8.18888131 3.55558367]
25 [8.18884161 3.45222704 8.18884161 3.53

2795
0
4153
[[6.09175468e-01 1.32202868e-01 2.36573022e-01 2.20486419e-02]
 [1.81074250e-01 2.10238589e-04 5.07426775e-01 3.11288737e-01]
 [6.49727506e-01 3.07359102e-02 1.17822370e-03 3.18358360e-01]
 ...
 [4.97230807e-01 1.86341407e-02 4.61216969e-01 2.29180833e-02]
 [3.59332300e-02 3.57187998e-01 4.35958663e-01 1.70920109e-01]
 [2.27905405e-01 3.31426674e-01 1.03686547e-02 4.30299266e-01]]
[8.61968291 3.0322299  0.49832682 3.75683679]
Init mean
[8.61968291 3.0322299  0.49832682 3.75683679]
Init s2
[0.81412312 0.41890995 0.91466706 0.86778217]
5 [8.09155268 3.4070762  0.08170059 3.54179173]
10 [8.0914637  3.46198204 0.08238434 3.48866599]
15 [8.09146049 3.47271216 0.08241866 3.47801136]
20 [8.09146036 3.47483701 0.08242001 3.47588949]
25 [8.09146036 3.47525879 0.08242007 3.47546783]
30 [8.09146036 3.47534255 0.08242007 3.47538407]
35 [8.09146036 3.47535919 0.08242007 3.47536743]
40 [8.09146036 3.47536249 0.08242007 3.47536413]
ELBO converged with ll 477.792 at iteration 42
[[10.90842

7681
2748
8539
4279
[[0.34866012 0.22555577 0.33177941 0.09400471]
 [0.15755218 0.42381535 0.09456611 0.32406636]
 [0.15699602 0.31196583 0.14598291 0.38505524]
 ...
 [0.21572278 0.20360341 0.30263418 0.27803963]
 [0.16973679 0.41947148 0.15521183 0.25557991]
 [0.31482677 0.33050686 0.07102877 0.2836376 ]]
[7.84241353 2.99235773 8.73944757 4.69921601]
Init mean
[7.84241353 2.99235773 8.73944757 4.69921601]
Init s2
[0.10766684 0.65539473 0.00564273 0.60519732]
5 [8.08177669 3.32109439 8.09815675 3.6994586 ]
10 [8.08894285 3.44304121 8.08930406 3.57521851]
15 [8.08902008 3.48498534 8.0890281  3.53302799]
20 [8.08901094 3.50021558 8.08901112 3.51776559]
25 [8.08900928 3.50578079 8.08900929 3.51219609]
30 [8.08900905 3.50781552 8.08900905 3.5101608 ]
35 [8.08900902 3.50855942 8.08900902 3.50941681]
40 [8.08900902 3.50883139 8.08900902 3.50914484]
45 [8.08900902 3.50893082 8.08900902 3.50904541]
50 [8.08900902 3.50896717 8.08900902 3.50900906]
55 [8.08900902 3.50898046 8.08900902 3.50899577

5 [nan nan nan nan]
10 [nan nan nan nan]
15 [nan nan nan nan]
20 [nan nan nan nan]
25 [nan nan nan nan]
30 [nan nan nan nan]
35 [nan nan nan nan]
40 [nan nan nan nan]
45 [nan nan nan nan]
50 [nan nan nan nan]
55 [nan nan nan nan]
60 [nan nan nan nan]
65 [nan nan nan nan]
70 [nan nan nan nan]
75 [nan nan nan nan]
80 [nan nan nan nan]
85 [nan nan nan nan]
90 [nan nan nan nan]
95 [nan nan nan nan]
100 [nan nan nan nan]
ELBO ended with ll nan
[-5940414034300995.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
[[nan nan]]
[[4.03737671e+11 3.5987

2786
8642
4153
[[0.27803667 0.20447076 0.4349473  0.08254527]
 [0.08216697 0.02714921 0.8772718  0.01341202]
 [0.01411064 0.17408227 0.40085261 0.41095448]
 ...
 [0.42750332 0.27503607 0.1811749  0.1162857 ]
 [0.07621236 0.07626543 0.56658563 0.28093657]
 [0.09174971 0.19257957 0.40714081 0.30852991]]
[8.11128948 2.55683162 8.36661376 5.08345174]
Init mean
[8.11128948 2.55683162 8.36661376 5.08345174]
Init s2
[0.04942864 0.77586596 0.67834155 0.00607098]
5 [8.4247945  3.33370966 8.42546017 3.5992483 ]
10 [8.42497205 3.43917127 8.42497393 3.49354405]
15 [8.42496661 3.46069043 8.42496661 3.47201616]
20 [8.42496634 3.46517268 8.42496634 3.46753353]
25 [8.42496632 3.46610703 8.42496632 3.46659916]
30 [8.42496632 3.4663018  8.42496632 3.46640439]
35 [8.42496632 3.46634241 8.42496632 3.46636379]
40 [8.42496632 3.46635087 8.42496632 3.46635533]
45 [8.42496632 3.46635263 8.42496632 3.46635356]
ELBO converged with ll 1692.177 at iteration 45
[[10.90842225  3.67085169]]
[[10.22842445  7.68328638

2790
8510
4050
[[0.26254713 0.3653352  0.13152973 0.24058794]
 [0.23177598 0.16868536 0.27194093 0.32759773]
 [0.15431259 0.16067745 0.29564724 0.38936272]
 ...
 [0.28090711 0.23144884 0.20671737 0.28092668]
 [0.19479519 0.51477328 0.163774   0.12665754]
 [0.39696832 0.17938949 0.26109936 0.16254283]]
[7.77591334 3.14698168 8.23707499 3.82437509]
Init mean
[7.77591334 3.14698168 8.23707499 3.82437509]
Init s2
[0.00200265 0.76731414 0.27613346 0.18460176]
5 [8.15576723 3.37821487 8.15911224 3.44143652]
10 [8.15741153 3.40660891 8.15743575 3.41300266]
15 [8.15742338 3.40948204 8.15742356 3.41012912]
20 [8.15742347 3.40977283 8.15742347 3.40983832]
25 [8.15742347 3.40980226 8.15742347 3.40980889]
30 [8.15742347 3.40980524 8.15742347 3.40980591]
ELBO converged with ll 1733.616 at iteration 30
[[10.90842225  3.67085141]]
[[10.04636037  7.36415398]]
7905
3099
8431
4326
[[0.03829799 0.01002737 0.17910301 0.77257163]
 [0.08075787 0.05145802 0.84948655 0.01829756]
 [0.18771788 0.44359579 0.0703

4246
[[0.37486896 0.25370744 0.22093339 0.15049021]
 [0.30567128 0.2573681  0.17745995 0.25950067]
 [0.2025413  0.26551829 0.33105722 0.20088319]
 ...
 [0.24653305 0.20586222 0.16682889 0.38077584]
 [0.13221513 0.31169781 0.20870893 0.34737812]
 [0.20122399 0.25201184 0.27206906 0.27469511]]
[8.15519131 2.9681485  8.47834114 4.30800902]
Init mean
[8.15519131 2.9681485  8.47834114 4.30800902]
Init s2
[0.98877426 0.51933872 0.43132885 0.58818852]
5 [8.19744368 3.65137419 8.19872363 3.71472169]
10 [8.19806105 3.68117616 8.19806623 3.68485267]
15 [8.19806356 3.68290755 8.19806359 3.68312105]
20 [8.19806357 3.6830081  8.19806358 3.6830205 ]
25 [8.19806358 3.68301394 8.19806358 3.68301466]
ELBO converged with ll 1846.752 at iteration 26
[[10.90842225  3.67085133]]
[[10.13843162  7.2863394 ]]
7924
3141
8454
4261
[[0.29114533 0.23473578 0.25078191 0.22333698]
 [0.45017991 0.18503794 0.08997473 0.27480742]
 [0.60350047 0.04781031 0.17372196 0.17496727]
 ...
 [0.24662641 0.2408969  0.25417447 0.

4443
[[0.1080057  0.45256723 0.24801938 0.19140769]
 [0.18751208 0.4120446  0.11858227 0.28186105]
 [0.32993237 0.28500631 0.16809853 0.21696278]
 ...
 [0.26339712 0.19530456 0.18294778 0.35835053]
 [0.1333265  0.20820525 0.37426683 0.28420142]
 [0.24727087 0.30978851 0.19702643 0.24591419]]
[8.03839651 2.88797474 7.78132566 4.60223057]
Init mean
[8.03839651 2.88797474 7.78132566 4.60223057]
Init s2
[0.44059336 0.4143868  0.40763444 0.37613466]
5 [8.08351468 3.37603905 8.08045568 3.85628064]
10 [8.08066362 3.50228349 8.08062514 3.72654023]
15 [8.08037669 3.55814784 8.0803762  3.67005423]
20 [8.0803109  3.58567847 8.08031089 3.64237437]
25 [8.08029414 3.59959043 8.08029414 3.62842444]
30 [8.08028982 3.60666324 8.08028982 3.62134184]
35 [8.08028869 3.61026408 8.08028869 3.61773846]
40 [8.0802884  3.61209783 8.0802884  3.61590405]
45 [8.08028833 3.61303171 8.08028833 3.61497   ]
50 [8.08028831 3.6135073  8.08028831 3.61449437]
55 [8.0802883  3.6137495  8.0802883  3.61425216]
60 [8.0802883

4171
[[0.23096228 0.2757732  0.19897506 0.29428946]
 [0.23611075 0.24374021 0.42486544 0.0952836 ]
 [0.17628324 0.12119775 0.39788291 0.30463611]
 ...
 [0.14243951 0.42096103 0.25756995 0.17902951]
 [0.16827144 0.39160427 0.12075244 0.31937185]
 [0.2817929  0.17440747 0.36259828 0.18120135]]
[7.99687943 1.63792065 8.62854992 4.01715871]
Init mean
[7.99687943 1.63792065 8.62854992 4.01715871]
Init s2
[0.55924449 0.26302193 0.36841047 0.15352903]
5 [8.09325603 3.39911633 8.09869404 3.61364291]
10 [8.09568285 3.48783308 8.09573329 3.52421867]
15 [8.09570007 3.50289912 8.09570054 3.509133  ]
20 [8.09570007 3.5054816  8.09570008 3.50654995]
25 [8.09570007 3.50592422 8.09570007 3.50610731]
30 [8.09570007 3.50600007 8.09570007 3.50603145]
35 [8.09570007 3.50601308 8.09570007 3.50601845]
40 [8.09570007 3.5060153  8.09570007 3.50601622]
ELBO converged with ll 1659.243 at iteration 40
[[10.90842226  3.6708513 ]]
[[10.10498394  7.28554354]]
7821
2795
8393
4176
[[0.14164372 0.14250548 0.44635367 0

4054
[[9.46331146e-01 4.00340035e-02 8.22144749e-03 5.41340305e-03]
 [1.51143722e-04 1.11862526e-01 4.02343607e-01 4.85642723e-01]
 [9.25618562e-01 1.38404794e-04 7.36854138e-03 6.68744923e-02]
 ...
 [5.14242583e-01 2.58466969e-01 1.72947617e-01 5.43428310e-02]
 [1.97393420e-01 6.85198821e-01 1.17369457e-01 3.83010732e-05]
 [9.16046323e-01 2.17695733e-06 8.37536919e-02 1.97808013e-04]]
[6.98372234 2.77742548 8.13610802 3.65679499]
Init mean
[6.98372234 2.77742548 8.13610802 3.65679499]
Init s2
[0.78129491 0.84097532 0.66867482 0.57956424]
5 [7.78985363 3.16855777 7.79844852 3.41230196]
10 [7.79380917 3.24851319 7.79386997 3.3315954 ]
15 [7.79380216 3.27561177 7.79380259 3.30441097]
20 [7.79379791 3.28500492 7.79379791 3.29500755]
25 [7.79379737 3.28826813 7.79379737 3.2917431 ]
30 [7.79379731 3.28940191 7.79379731 3.29060917]
35 [7.7937973  3.28979582 7.7937973  3.29021524]
40 [7.7937973  3.28993267 7.7937973  3.29007839]
45 [7.7937973  3.28998022 7.7937973  3.29003084]
50 [7.7937973  

7132
2650
0
4410
[[0.12767415 0.31933807 0.33845898 0.21452881]
 [0.20534488 0.24152507 0.19848249 0.35464756]
 [0.18132773 0.15962243 0.25019595 0.40885389]
 ...
 [0.31191308 0.22889387 0.08270656 0.37648649]
 [0.25884001 0.20364616 0.20199039 0.33552344]
 [0.17184141 0.27660474 0.28905605 0.2624978 ]]
[ 7.96215783  3.06105793 -0.59525838  4.57092585]
Init mean
[ 7.96215783  3.06105793 -0.59525838  4.57092585]
Init s2
[0.90149052 0.93835937 0.28348656 0.24002109]
5 [7.03370828 3.03333803 0.12173272 4.01586471]
10 [7.02154689 3.1482761  0.12711691 3.88927203]
15 [7.01860787 3.20945133 0.13096238 3.83132356]
20 [7.01709626 3.24696358 0.13299445 3.79544681]
25 [7.01616427 3.27274147 0.13422878 3.77061029]
30 [7.01553387 3.2917488  0.13505651 3.7522143 ]
35 [7.01507994 3.30644338 0.13564937 3.73794847]
40 [7.01473798 3.31819676 0.13609439 3.72651218]
45 [7.01447143 3.32784139 0.13644035 3.71711133]
50 [7.01425807 3.33591516 0.13671674 3.70923066]
55 [7.01408359 3.34278278 0.1369424  3.702

75 [7.13246604 3.1734005  7.13246604 3.83779131]
80 [7.13246248 3.17345159 7.13246248 3.83772786]
85 [7.13246024 3.1734837  7.13246024 3.83768799]
90 [7.13245883 3.17350388 7.13245883 3.83766293]
95 [7.13245795 3.17351656 7.13245795 3.83764718]
100 [7.13245739 3.17352454 7.13245739 3.83763727]
ELBO ended with ll 1415.019
[-9691.83066046366, 1243.753894411107, 1375.0783150109983, 1398.1915100830245, 1406.0599115310715, 1409.6925344459985, 1411.6312907206948, 1412.7641839753326, 1413.4701059101947, 1413.9311393671294, 1414.242896808738, 1414.459304959676, 1414.6125762818697, 1414.7228466345705, 1414.80316357842, 1414.8622292902278, 1414.9059868513511, 1414.9385763296957, 1414.9629308825488, 1414.9811590390186, 1414.9947957872382, 1415.0049709335656, 1415.0125240582206, 1415.0180842843758, 1415.0221264380802, 1415.0250111068176, 1415.0270135534715, 1415.028344811819, 1415.02916722912, 1415.0296060198261, 1415.029757924007, 1415.0296977439064, 1415.0294833117428, 1415.029159288032, 1415.02

2846
6916
4419
[[0.10953198 0.46732395 0.38318471 0.03995936]
 [0.3082324  0.43696315 0.17632544 0.07847901]
 [0.3625789  0.26428219 0.13017855 0.24296035]
 ...
 [0.10715785 0.19162554 0.33777418 0.36344244]
 [0.27024804 0.2914126  0.08655805 0.35178131]
 [0.15678566 0.17755684 0.4375541  0.2281034 ]]
[0.60080281 2.42112621 7.27078189 4.60993333]
Init mean
[0.60080281 2.42112621 7.27078189 4.60993333]
Init s2
[0.19426933 0.00134629 0.73548356 0.77270491]
5 [0.07867374 3.25736508 6.76204324 4.03386315]
10 [0.08266589 3.41977051 6.74525219 3.82856482]
15 [0.0842469  3.50405524 6.7416775  3.7379493 ]
20 [0.08478873 3.55149018 6.74061131 3.6887579 ]
25 [0.08497605 3.57921089 6.74025271 3.66045839]
30 [0.0850417  3.5956189  6.74012802 3.6438505 ]
35 [0.08506483 3.60536878 6.74008419 3.63403053]
40 [0.085073   3.61116803 6.74006873 3.62820657]
45 [0.08507589 3.61461784 6.74006327 3.62474803]
50 [0.08507691 3.61666982 6.74006134 3.62269297]
55 [0.08507727 3.61789022 6.74006066 3.62147148]
60 

5797
3347
6603
0
[[0.16083045 0.62112165 0.12454814 0.09349976]
 [0.43534061 0.0814543  0.18582319 0.2973819 ]
 [0.31464637 0.37257416 0.15110517 0.16167431]
 ...
 [0.40234877 0.09106856 0.1744978  0.33208487]
 [0.35407844 0.19178205 0.10330803 0.35083148]
 [0.33855165 0.10622935 0.28695662 0.26826238]]
[5.03837233 3.52685767 6.06935083 0.35145906]
Init mean
[5.03837233 3.52685767 6.06935083 0.35145906]
Init s2
[0.87025924 0.74137649 0.61395343 0.95862886]
5 [6.04209917e+00 3.43635071e+00 6.18802187e+00 5.73711494e-03]
10 [6.11754071 3.44320175 6.12811386 0.00638725]
15 [6.12251282 3.44332932 6.1232731  0.00640349]
20 [6.12286622 3.44333085 6.12292089 0.0064037 ]
25 [6.12289159 3.44333086 6.12289553 0.0064037 ]
30 [6.12289342 3.44333086 6.1228937  0.0064037 ]
ELBO converged with ll 859.684 at iteration 30
[[10.90842258  3.6708497 ]]
[[10.64035039  5.69511601]]
0
3306
6457
4911
[[0.47881667 0.12307871 0.20442931 0.19367531]
 [0.59054122 0.07078519 0.06770548 0.27096812]
 [0.05559927 0.3

[[0.30808036 0.22929732 0.2810248  0.18159751]
 [0.16969773 0.24045275 0.34345127 0.24639825]
 [0.45354069 0.30211432 0.07760913 0.16673586]
 ...
 [0.24356465 0.0763932  0.56045565 0.1195865 ]
 [0.51492547 0.22235458 0.14151418 0.12120577]
 [0.11128882 0.33250522 0.36363754 0.19256842]]
[-0.64590298  3.35667515  6.16697919  4.79352964]
Init mean
[-0.64590298  3.35667515  6.16697919  4.79352964]
Init s2
[0.77636191 0.25465192 0.21822027 0.42079502]
5 [0.02268894 3.90295029 5.85839952 5.32819142]
10 [0.02313773 3.88227891 5.75235555 5.50495116]
15 [0.02293453 3.87425212 5.69305505 5.57922451]
20 [0.02288962 3.87257381 5.66378892 5.61159163]
25 [0.02288042 3.87222652 5.64997419 5.6260542 ]
30 [0.02287851 3.87215395 5.64356221 5.63260202]
35 [0.0228781  3.87213874 5.64060729 5.63558544]
40 [0.02287802 3.87213554 5.63924984 5.63694889]
45 [0.022878   3.87213487 5.63862712 5.63757286]
50 [0.022878   3.87213473 5.63834165 5.6378586 ]
55 [0.022878   3.8721347  5.63821081 5.63798949]
60 [0.0228

4644
3895
5839
5413
[[1.29748051e-05 2.52735941e-08 7.30233281e-08 9.99986927e-01]
 [7.02356309e-03 9.90620053e-01 1.91216610e-03 4.44218007e-04]
 [2.64278039e-19 1.54413999e-01 1.05104017e-02 8.35075599e-01]
 ...
 [8.81334974e-07 5.35947234e-03 2.35537216e-05 9.94616093e-01]
 [9.98174377e-01 2.48257964e-05 1.14381055e-03 6.56986348e-04]
 [9.99997870e-01 3.55918097e-08 2.09455043e-06 9.62491443e-18]]
[4.77370681 4.46212568 5.63122816 4.87656922]
Init mean
[4.77370681 4.46212568 5.63122816 4.87656922]
Init s2
[0.48440021 0.40458109 0.9054385  0.16173741]
5 [4.88815124 4.79244025 5.09955378 4.91911827]
10 [4.91303087 4.87952999 4.98286105 4.92366423]
15 [4.92079845 4.90909084 4.94472703 4.92448548]
20 [4.92340806 4.91933639 4.93167365 4.92468667]
25 [4.92430332 4.92289036 4.92716493 4.92474658]
30 [4.92461252 4.92412259 4.92560395 4.92476616]
35 [4.92471956 4.92454973 4.92506313 4.92477281]
40 [4.92475664 4.92469778 4.92487571 4.9247751 ]
45 [4.92476949 4.92474909 4.92481076 4.92477589]


0
[[0.29517944 0.30590227 0.29282077 0.10609752]
 [0.23073027 0.37344517 0.25823278 0.13759178]
 [0.28799482 0.27600997 0.27799411 0.1580011 ]
 ...
 [0.18240963 0.20392198 0.29308808 0.32058031]
 [0.11538599 0.20236833 0.13052847 0.5517172 ]
 [0.1860077  0.17085975 0.23714345 0.40598911]]
[ 4.879044    3.95590923 -0.60698517  0.87622675]
Init mean
[ 4.879044    3.95590923 -0.60698517  0.87622675]
Init s2
[0.12291589 0.29453818 0.34514816 0.60865416]
5 [4.2740341  4.27284007 0.00909056 0.01132487]
10 [4.2734379  4.27343625 0.01020565 0.01020917]
ELBO converged with ll 2215.505 at iteration 13
[[10.90842371  3.67084767]]
[[12.29141516  3.67237414]]
4256
4335
0
5689
[[0.24192345 0.22004393 0.31232005 0.22571257]
 [0.06217493 0.08894534 0.46240291 0.38647682]
 [0.22998308 0.23932413 0.086266   0.44442678]
 ...
 [0.41125869 0.13366623 0.26157984 0.19349524]
 [0.42668863 0.10509076 0.07483919 0.39338142]
 [0.172277   0.225637   0.33173554 0.27035046]]
[ 4.11423201  4.65199412 -0.04292722  5.

65 [4.99898114 4.99909721 4.99903986 4.9993083 ]
70 [4.99903923 4.99910157 4.99907077 4.99921495]
75 [4.99907043 4.99910391 4.99908737 4.99916481]
80 [4.99908718 4.99910517 4.99909628 4.99913788]
85 [4.99909618 4.99910584 4.99910107 4.99912341]
90 [4.99910102 4.99910621 4.99910364 4.99911564]
95 [4.99910362 4.9991064  4.99910503 4.99911147]
100 [4.99910501 4.99910651 4.99910577 4.99910923]
ELBO ended with ll 3727.579
[-1104.3833681090878, 3148.929338220578, 3588.4716973385043, 3674.299475103374, 3697.6890781353036, 3708.4845620413494, 3714.569913374094, 3718.350880500538, 3720.8536587637773, 3722.584822068936, 3723.820495373377, 3724.722929821308, 3725.393233659124, 3725.897429149489, 3726.2802765099223, 3726.5730515305936, 3726.7981444461616, 3726.9718983210287, 3727.1064276611182, 3727.2108225268425, 3727.291969050956, 3727.3551227302446, 3727.4043176914456, 3727.4426642367216, 3727.472568482269, 3727.4958965283167, 3727.514098417061, 3727.5283024876367, 3727.539387656678, 3727.54803

3783
4860
5164
6237
[[0.31180401 0.31894717 0.16605756 0.20319126]
 [0.25115441 0.14779198 0.29485017 0.30620345]
 [0.18923523 0.53819431 0.03655935 0.2360111 ]
 ...
 [0.08585388 0.35365575 0.37893065 0.18155972]
 [0.16152366 0.45578957 0.2689572  0.11372957]
 [0.33872834 0.27574631 0.33524547 0.05027988]]
[3.30346156 5.1708624  4.84361153 5.90733521]
Init mean
[3.30346156 5.1708624  4.84361153 5.90733521]
Init s2
[0.39656613 0.09581446 0.5025524  0.28983829]
5 [4.47167534 5.11921419 4.96565798 5.41962253]
10 [4.60822942 5.09097366 4.967355   5.31355429]
15 [4.66769542 5.07852301 4.96803743 5.26651494]
20 [4.70184363 5.07148602 4.96830089 5.23940235]
25 [4.72413875 5.06702182 4.96830863 5.22170264]
30 [4.73982303 5.06400964 4.96814434 5.20928012]
35 [4.75140754 5.06190826 4.96785635 5.2001421 ]
40 [4.76026187 5.06042066 4.96747485 5.19319739]
45 [4.76720311 5.05936871 4.96701984 5.18779301]
50 [4.77275195 5.05863839 4.96650525 5.18351182]
55 [4.77725739 5.05815292 4.96594112 5.18007361

3642
0
5169
6274
[[0.33828096 0.15234853 0.37886003 0.13051048]
 [0.00892212 0.08594553 0.3898894  0.51524295]
 [0.33895022 0.40811483 0.17384889 0.07908606]
 ...
 [0.24987491 0.34686453 0.03531049 0.36795008]
 [0.29745057 0.52835085 0.03976713 0.13443145]
 [0.38991186 0.23932653 0.01898849 0.35177312]]
[4.42591116 0.36620901 4.71447771 6.34102641]
Init mean
[4.42591116 0.36620901 4.71447771 6.34102641]
Init s2
[0.37630932 0.74349321 0.84087409 0.33923313]
5 [4.31686659 0.04041567 4.79860962 5.89081291]
10 [4.17861699 0.03856772 4.99742848 5.85290394]
15 [4.06419993 0.0358878  5.20443974 5.78737075]
20 [4.01228364 0.03438352 5.34801899 5.71261574]
25 [3.99437877 0.03385001 5.43187276 5.65405966]
30 [3.98830061 0.03367431 5.48014538 5.61474933]
35 [3.9861604  0.03361385 5.5083439  5.58977148]
40 [3.98538985 0.0335923  5.52502307 5.57426137]
45 [3.98510981 0.0335845  5.53497046 5.56474015]
50 [3.98500767 0.03358166 5.54093411 5.55893211]
55 [3.98497036 0.03358062 5.54452107 5.55540201]
6

55 [4.43617102 5.1848988  5.23058277 5.23969254]
60 [4.43538133 5.19170199 5.22856893 5.23568489]
65 [4.43485702 5.1971916  5.22685269 5.23243016]
70 [4.43451229 5.20160579 5.22541275 5.22979674]
75 [4.43428733 5.20514604 5.2242188  5.22767274]
80 [4.4341414  5.20797992 5.2232377  5.22596411]
85 [4.4340472  5.21024511 5.22243709 5.22459257]
90 [4.43398661 5.21205379 5.22178727 5.22349353]
95 [4.43394776 5.21349679 5.22126206 5.2226141 ]
100 [4.43392292 5.21464734 5.22083895 5.22191118]
ELBO ended with ll 3348.609
[-791.2603633867981, 3160.625003157756, 3302.0385177057574, 3328.740277361291, 3338.133875793049, 3342.3086985590494, 3344.4267365558358, 3345.6059983668356, 3346.311544900644, 3346.759689299962, 3347.059817665725, 3347.270915662128, 3347.426431177655, 3347.5461035319104, 3347.641961864306, 3347.7215305449886, 3347.7896185056134, 3347.849355369601, 3347.902810272045, 3347.951371216508, 3347.99598279427, 3348.03729790016, 3348.0757760266556, 3348.1117477190655, 3348.14545723454

5037
5164
6415
[[0.388267   0.41138849 0.08847698 0.11186754]
 [0.29056773 0.19854226 0.40364929 0.10724072]
 [0.35874037 0.24113633 0.30648094 0.09364236]
 ...
 [0.20241703 0.20984278 0.24208651 0.34565368]
 [0.10802715 0.25530918 0.12493439 0.51172927]
 [0.24550525 0.31905313 0.36222047 0.07322115]]
[3.46634877 5.66676203 5.72715951 6.05634264]
Init mean
[3.46634877 5.66676203 5.72715951 6.05634264]
Init s2
[0.10347577 0.98679446 0.88617309 0.78049813]
5 [4.22293252 5.27601601 5.30976786 5.47788731]
10 [4.27271484 5.26996746 5.30207924 5.44824231]
15 [4.27949415 5.27264559 5.3043619  5.43728781]
20 [4.27992422 5.27638527 5.30782152 5.4298461 ]
25 [4.27940977 5.28001002 5.31111788 5.42352395]
30 [4.27882948 5.28336145 5.31407351 5.41785633]
35 [4.27831439 5.28644734 5.31670059 5.41270673]
40 [4.27787265 5.28929759 5.3190368  5.40800302]
45 [4.27749458 5.29194077 5.32111846 5.40369151]
50 [4.27716974 5.29440114 5.32297707 5.39972785]
55 [4.27688937 5.29669898 5.32463954 5.39607439]
60 

70 [4.21909784 0.00865173 5.45544837 5.47214894]
75 [4.21906738 0.00865139 5.4574998  5.4701334 ]
80 [4.21904995 0.00865119 5.45904838 5.46860535]
85 [4.21903997 0.00865108 5.46021797 5.46744752]
90 [4.21903427 0.00865102 5.46110164 5.46657057]
95 [4.219031   0.00865098 5.4617695  5.46590656]
100 [4.21902913 0.00865096 5.46227436 5.4654039 ]
ELBO ended with ll 1313.750
[-18409.967226155346, 1266.1119116538878, 1301.1052015224693, 1306.1860500341393, 1307.6440345384326, 1308.4095755596331, 1308.9628728042628, 1309.4257900953442, 1309.8380877376414, 1310.2138496966213, 1310.5583446122691, 1310.8739148346417, 1311.1620935043231, 1311.4243231092328, 1311.662149581508, 1311.877229092104, 1312.0712788131864, 1312.2460210190402, 1312.4031369593993, 1312.5442339852273, 1312.6708247147394, 1312.7843157062869, 1312.8860030854498, 1312.9770729846898, 1313.058605143588, 1313.1315784562373, 1313.196877604379, 1313.255300182248, 1313.3075639148267, 1313.3543137115628, 1313.3961283961737, 1313.433527

5112
6312
[[0.36804673 0.19109742 0.16728005 0.2735758 ]
 [0.34680996 0.11499358 0.20760891 0.33058755]
 [0.43122118 0.16410409 0.27577851 0.12889623]
 ...
 [0.14278917 0.21174563 0.59511969 0.0503455 ]
 [0.47047251 0.11330682 0.11962124 0.29659942]
 [0.32921161 0.06534483 0.34803308 0.25741049]]
[3.03918376 5.43226638 4.9716176  6.48757585]
Init mean
[3.03918376 5.43226638 4.9716176  6.48757585]
Init s2
[0.06730612 0.91748186 0.42442791 0.84416381]
5 [4.20892912 5.2038464  4.98540688 5.58236389]
10 [4.26946429 5.21380611 5.0019726  5.50374807]
15 [4.27239922 5.23124647 5.01366249 5.47297398]
20 [4.26764887 5.24728798 5.02314958 5.45268105]
25 [4.26281885 5.26072364 5.03103369 5.43647405]
30 [4.25894299 5.27177176 5.0377218  5.42281888]
35 [4.25592474 5.28084524 5.04352287 5.41112519]
40 [4.25354449 5.28831058 5.04866474 5.40103208]
45 [4.25162435 5.29446044 5.05331297 5.39226704]
50 [4.25003741 5.29952541 5.05758767 5.38461148]
55 [4.2486949  5.30368869 5.06157638 5.37788721]
60 [4.24

85 [4.13793902 0.01470804 5.53320844 5.5359252 ]
90 [4.13793832 0.01470802 5.53358359 5.53555097]
95 [4.13793795 0.01470802 5.53385517 5.53527988]
100 [4.13793776 0.01470802 5.53405179 5.53508351]
ELBO ended with ll 1225.179
[-18572.223832303807, 1162.1340412931468, 1212.2012991849806, 1218.3850249029274, 1220.1828911565515, 1221.0469280306347, 1221.626482993145, 1222.0848528295019, 1222.4727498751301, 1222.8091054336664, 1223.103012380851, 1223.3603055708463, 1223.5855711544082, 1223.7827485764944, 1223.9553105852694, 1224.106327173313, 1224.2385032525435, 1224.3542128561537, 1224.4555334756337, 1224.5442796682585, 1224.622034686995, 1224.690179363042, 1224.7499179466076, 1224.8023009239619, 1224.8482449989224, 1224.8885505038782, 1224.9239165273418, 1224.9549540381104, 1224.9821972647646, 1225.0061135627743, 1225.027111973605, 1225.045550654023, 1225.0617433297255, 1225.0759649062004, 1225.08845635112, 1225.0994289464952, 1225.109067995078, 1225.1175360535708, 1225.1249757551902, 122

6307
[[0.0768948  0.17390009 0.33333263 0.41587248]
 [0.18356398 0.32781866 0.0571644  0.43145295]
 [0.11975248 0.1897253  0.21013688 0.48038534]
 ...
 [0.15927614 0.13737254 0.28531918 0.41803213]
 [0.17565925 0.17913205 0.32187222 0.32333648]
 [0.14066809 0.20743248 0.44597061 0.20592881]]
[3.11831086 4.10079959 4.87884822 6.36898483]
Init mean
[3.11831086 4.10079959 4.87884822 6.36898483]
Init s2
[0.07020675 0.40765284 0.66597481 0.7707995 ]
5 [4.59330394 4.82815847 5.09683878 5.60452963]
10 [4.70778418 4.86055714 5.07148999 5.48029958]
15 [4.75584277 4.87280109 5.05831464 5.43293515]
20 [4.7827903  4.87851777 5.04891998 5.40963692]
25 [4.80020071 4.88134761 5.04119506 5.39712299]
30 [4.81249623 4.88272506 5.03434135 5.39030797]
35 [4.82175377 4.88333986 5.02799676 5.38678252]
40 [4.82907914 4.88356363 5.02198206 5.38524804]
45 [4.83511179 4.88360961 5.01620586 5.38494374]
50 [4.84024318 4.88360341 5.01062246 5.38539888]
55 [4.84472288 4.88361848 5.00521094 5.38631185]
60 [4.8487148

40 [4.8326304  4.8326665  4.83293954 6.08705398]
45 [4.83270284 4.83271617 4.83281706 6.08705445]
50 [4.83272963 4.83273455 4.83277183 6.08705453]
55 [4.83273953 4.83274135 4.83275512 6.08705454]
60 [4.83274319 4.83274386 4.83274895 6.08705454]
65 [4.83274454 4.83274479 4.83274667 6.08705454]
ELBO converged with ll 3243.952 at iteration 67
[[10.90842199  3.67084735]]
[[9.98266771 2.86774964]]
3722
4958
5164
6284
[[0.12574699 0.29555038 0.57062529 0.00807735]
 [0.10442821 0.24793348 0.42882549 0.21881282]
 [0.49257732 0.07998668 0.36044476 0.06699124]
 ...
 [0.09961966 0.60236961 0.10400574 0.19400498]
 [0.314046   0.14888185 0.21321608 0.32385606]
 [0.17438996 0.37320073 0.30132421 0.1510851 ]]
[4.28836985 4.82771886 4.85110721 5.27156065]
Init mean
[4.28836985 4.82771886 4.85110721 5.27156065]
Init s2
[0.48386299 0.05008731 0.50090314 0.34372249]
5 [4.49381645 5.06535523 5.08995326 5.48487564]
10 [4.48119084 5.07797681 5.10459058 5.47048423]
15 [4.47073658 5.08900281 5.11757145 5.4571

60 [4.54561907 5.37347167 4.88607978 5.37715082]
65 [4.55015566 5.37580227 4.87728839 5.37900245]
70 [4.55471518 5.3779867  4.86871827 5.38075947]
75 [4.55928059 5.38002635 4.86038717 5.38241995]
80 [4.5638352  5.38192417 4.85230958 5.38398322]
85 [4.56836309 5.38368428 4.84449689 5.38544973]
90 [4.5728494  5.38531179 4.83695749 5.38682082]
95 [4.57728047 5.38681254 4.82969699 5.38809867]
100 [4.58164396 5.3881929  4.82271847 5.3892861 ]
ELBO ended with ll 3299.433
[-658.5915449349108, 3101.8695468202573, 3255.738118975979, 3282.528266291973, 3291.451236690129, 3295.1393555107816, 3296.892833335247, 3297.804995090629, 3298.3096809567505, 3298.601742101111, 3298.77670885229, 3298.884556210289, 3298.9527516846406, 3298.9969812717227, 3299.0264753060574, 3299.0467946606145, 3299.0613518277773, 3299.0722710144382, 3299.080888825801, 3299.088052830375, 3299.094303180595, 3299.0999849220552, 3299.1053183799013, 3299.1104437513777, 3299.115449600203, 3299.120391184533, 3299.1253023021554, 329

15 [4.26951217 4.74908132 0.01790261 5.89686685]
20 [4.28577761 4.72431651 0.01794728 5.90237095]
25 [4.30033227 4.70314889 0.01798608 5.90659168]
30 [4.31338872 4.68483694 0.01801899 5.90991091]
35 [4.3251566  4.6688277  0.01804689 5.91256687]
40 [4.3358152  4.6547008  0.01807062 5.91472346]
45 [4.34551464 4.64213275 0.01809089 5.91649669]
50 [4.35437984 4.6308715  0.01810826 5.91797049]
55 [4.3625148  4.62071813 0.01812322 5.91920681]
60 [4.37000641 4.61151368 0.01813614 5.92025222]
65 [4.3769276  4.60312962 0.01814735 5.92114233]
70 [4.38334    4.59546089 0.0181571  5.92190476]
75 [4.38929601 4.58842067 0.01816561 5.92256123]
80 [4.39484049 4.58193655 0.01817306 5.92312904]
85 [4.40001209 4.57594756 0.01817959 5.92362212]
90 [4.40484432 4.57040195 0.01818533 5.92405181]
95 [4.40936645 4.56525543 0.01819039 5.9244274 ]
100 [4.41360416 4.56046983 0.01819485 5.92475659]
ELBO ended with ll 1180.691
[-15211.389303186828, 1103.5681383123965, 1172.3017305337678, 1177.2187444724445, 1178.62

60 [4.62295251 5.41770329 4.71376508 5.46260699]
65 [4.62585822 5.421414   4.71008163 5.45966522]
70 [4.62861317 5.42457052 4.70669408 5.45713345]
75 [4.63121325 5.4272542  4.7035772  5.45495964]
80 [4.63365844 5.42953497 4.70070795 5.45309683]
85 [4.63595152 5.4314728  4.69806533 5.4515032 ]
90 [4.63809722 5.43311893 4.6956303  5.45014175]
95 [4.64010149 5.43451706 4.69338556 5.44898005]
100 [4.64197101 5.43570444 4.69131543 5.44798977]
ELBO ended with ll 3257.388
[-2907.2174753806535, 2991.148800036159, 3210.646628008169, 3241.3307931985037, 3250.1559266320805, 3253.6008079345597, 3255.179412398949, 3255.973353324773, 3256.399628036875, 3256.6408114058045, 3256.783933712276, 3256.8731017015243, 3256.931704440685, 3256.972572374053, 3257.002925212372, 3257.026903460752, 3257.046915299071, 3257.0643758063584, 3257.080122778472, 3257.0946551670127, 3257.1082718309704, 3257.1211531577846, 3257.133409434123, 3257.1451096339642, 3257.156298572393, 3257.1670071063995, 3257.1772581666323, 32

KeyboardInterrupt: 

In [ ]:
print(X[0])

In [ ]:
K = X[0]
K = np.append(K,X[SAMPLE])
K = np.append(K,X[2*SAMPLE])
K = np.append(K,X[3*SAMPLE])
print(K)

In [ ]:
pip install pypozyx

In [ ]:
pip install pyserial

In [20]:
print(type(float(zd[0][1])))

<class 'float'>


In [33]:
print(zd)

[[3.371 5.178 5.553 6.701]]


In [28]:
print(zd)

[[3.38  4.672 5.45  6.757]]


In [34]:
print(zd_2)

[[3.66556318 5.74464315 5.74460338 5.74473534]]
